services:

  sonarr:
    image: ghcr.io/wepwawet/anisette:latest  # актуальный форк AnimeSonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}       
      - PGID=${PGID}  
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./config:/config
      - ${LOAD_PATH}:/anime    
      - ${LOAD_PATH}:/downloads
    ports:
      - "127.0.0.1:8989:8989" # Биндим только на localhost, так как снаружи будет Nginx
    restart: unless-stopped
    networks:
      - hcp-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}       
      - PGID=${PGID}  
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - hcp-network

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Asia/Yekaterinburg
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - hcp-network

networks:
  hcp-network:
    external: true

