# Определение зоны кеширования для Authentik (ускоряет повторные проверки)
proxy_cache_path /var/cache/nginx/authentik levels=1:2 keys_zone=authentik:10m max_size=10m inactive=60m use_temp_path=off;

server {
    listen 80;
    listen [::]:80;
    server_name sonar.leonet.site;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sonar.leonet.site;
    include snippets/sslpath.conf;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    include snippets/authentikoutpost.conf;
    location / {
        include snippets/authentikcheck.conf;

        # Передача данных пользователя из Authentik в Sonarr (для логов/прав)
        auth_request_set $user $upstream_http_x_authentik_username;
        proxy_set_header X-Authentik-Username $user;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass       http://sonarr:8989;
    }

    include snippets/authentikunauthorized.conf;
}

